---
version: 3.7.3
name: Feedly • Simple, fast and secure
description: Feedly without images
repository: https://github.com/SidVal/feedly-no-img
timezone: America/Argentina/Buenos_Aires
logo: "/assets/feedly-no-img.png"
theme: jekyll-theme-time-machine
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
sass:
  style: compressed
exclude:
- ".gitignore"
